"""Add Pesapal tracking fields to deposits

Revision ID: 8d570889c411
Revises: 8dd32d3f8686
Create Date: 2026-07-19 10:07:06.005068

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8d570889c411'
down_revision = '8dd32d3f8686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pesapal_order_tracking_id', sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column('pesapal_merchant_reference', sa.String(length=100), nullable=True)
        )

        batch_op.create_unique_constraint(
            'uq_deposits_pesapal_order_tracking_id',
            ['pesapal_order_tracking_id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposits', schema=None) as batch_op:

        batch_op.drop_constraint(
            'uq_deposits_pesapal_order_tracking_id',
            type_='unique'
        )

        batch_op.drop_column('pesapal_merchant_reference')
        batch_op.drop_column('pesapal_order_tracking_id')
    # ### end Alembic commands ###
